# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    admin.test:
        class: AppBundle\Admin\TestAdmin
        arguments: [~, AppBundle\Entity\Test, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Test }
    admin.testquestion:
        class: AppBundle\Admin\TestQuestionAdmin
        arguments: [~, AppBundle\Entity\Test, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Test Questions', show_in_dashboard: false }
    admin.question:
        class: AppBundle\Admin\QuestionAdmin
        arguments: [~, AppBundle\Entity\Question, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Question, show_in_dashboard: false }
    admin.kind:
        class: AppBundle\Admin\KindAdmin
        arguments: [~, AppBundle\Entity\Kind, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Kind, show_in_dashboard: false }
    admin.option:
        class: AppBundle\Admin\OptionAdmin
        arguments: [~, AppBundle\Entity\Option, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Option, show_in_dashboard: false }